baseurl: "buec311.aleach.ca"
languageCode: "en-us"
title: "Business Economics, Organizations and Management"
theme: "rvs-tufte-hugo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: "syllabus-311.pdf"
      weight: 1
    - name: Assignments
      url: assignments/
      weight: 3
    - name: Schedule
      url: schedule/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 5
    - name: eClass
      url: "https://eclass.srv.ualberta.ca/portal/"
      weight: 7
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Leach
  thumbnail: /images/gas_demand.png
  instructor: 
    name: Andrew Leach
    email: aleach@ualberta.ca
    url: "https://www.aleach.ca"
    twitter: andrew_leach
    github: leachandrew
    office: 3-20D Business
  course:
    number: BUEC 311
    semester: Fall 2021
    twitter: andrew_leach
    dates: "September 1–Dec 8, 2021"
    github: "leachandrew/buec_311_f21"
    copyrightYear: "2021-2022"
    contactDetails: >-
      Office hours: See syllabus
  university: 
    name: University of Alberta
    url: "https://www.ualberta.ca"
  school:
    name: Alberta School of Business
    url: "https://www.ualberta.ca/business/index.html"
  description: "Business Economics, Organizations and Management"
  primaryColor: "#007C41"
  secondaryColor: "#FFDB05"
  credits: >- 
    Course website based on those shared by [Ryan Safner](https://github.com/ryansafner) and [Andrew Heiss](https://econw19.classes.andrewheiss.com/).
  logo:
    url: /images/UA-ASB-COLOUR.png
    alt: Business Economics, Organizations and Management
  meta:
    twitterSite: "@andrew_leach"
    twitterCreator: "@andrew_leach"

markup:
  goldmark:
    renderer:
      unsafe: true
