---
title: First Quiz Data
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)

library(lubridate)
library(viridis)
library(zoo)
library(janitor)
library(broom)
library(ggthemes)
library(directlabels)
library(kableExtra)
library(stargazer)
library(scales)
library(ggrepel)
library(readxl)
library(tidyverse)


colors_tableau10<-function()
{
  return(c("#1F77B4", "#FF7F0E", "#2CA02C", "#D62728", "#9467BD", "#8C564B",
           "#E377C2", "#7F7F7F", "#BCBD22", "#17BECF"))
}

class_clean<-function(){
  theme_classic()+
    theme(
      plot.subtitle = element_text(color="grey10",size=rel(.7)),
      plot.title = element_text(face="bold",size=rel(.8)),
      plot.caption = element_text(color="grey50",size=rel(.5),hjust=0),
      legend.title = element_text(color="grey10",size=rel(.5)),
      legend.text = element_text(color="grey10",size=rel(.5)),
      axis.text = element_text(size=rel(1.5)),
      axis.title = element_text(size=rel(1.5)),
      #panel.grid.major = element_line(size=0,colour = "black"), 
      #plot.margin = margin(t = .1, r = .1, b = .1, l = .1,unit= "cm"),
      plot.margin = margin(t = .5, r = 1, b = .25, l = 1,unit= "cm"),
      #axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
      NULL)
}


```

```{r test_data,echo=FALSE,warnings=FALSE,include=FALSE,,cache=FALSE}
#load by sections
section_a3<-read_excel("../private/1770_48844.xls",skip = 1) %>% mutate(sec="A3")
section_a2<-read_excel("../private/1770_40844.xls",skip = 1) %>% mutate(sec="A2")
section_a1<-read_excel("../private/1770_40782.xls",skip = 1) %>% mutate(sec="A1")
sections<- bind_rows(section_a1,section_a2,section_a3) %>% select(student_id=ID,sec)%>%
  mutate(student_id=as.numeric(student_id))


test_data<-read_excel("../private/first_quiz.xlsx") %>% clean_names() %>% mutate(samples=as.factor((quiz_sample_quiz_number_1_real!="-")*1+
               (quiz_sample_quiz_number_2_real!="-")*1+
               (quiz_sample_quiz_3_real!="-")*1))%>%
  select(samples,grade=first_quiz,student_id) %>% left_join(sections)

test_A1<-test_data %>% filter(sec=="A1")
test_A2<-test_data %>% filter(sec=="A2")
test_A3<-test_data %>% filter(sec=="A3")

```
The average over all three sections was `r round(mean(test_data$grade,na.rm=T),2)`%.

The averages for the individual sections were `r round(mean(test_A1$grade,na.rm=T),2)`% for section A1, `r round(mean(test_A2$grade,na.rm=T),2)`% for section A2 and `r round(mean(test_A3$grade,na.rm=T),2)`% for section A3.

```{r test_graphs,echo=FALSE,warnings=FALSE,include=FALSE,,cache=FALSE}

all<-ggplot(test_data%>%filter(!is.na(grade)),aes(grade))+
  geom_density(aes(),alpha=0.5,fill="dodgerblue")+
  labs(x="Range of Scores",y="Probability Density",
       title="Distribution of midterm Scores",
       caption="Kernel-smoothed so you won't necessarily find your actual grade",
       fill=guide_legend(title="Section"),color=guide_legend(title="Section"))


sec<-ggplot(test_data%>%filter(!is.na(grade)),aes(grade,group=sec))+
  geom_density(aes(fill=sec,colour=sec),alpha=0.5)+
  labs(x="Range of Scores",y="Probability Density",
       title="Distribution of midterm Scores by Section",
       caption="Kernel-smoothed so you won't necessarily find your actual grade",
       fill=guide_legend(title="Section"),color=guide_legend(title="Section"))


samples<-ggplot(test_data%>%filter(!is.na(grade)),aes(grade,group=samples))+
  geom_density(aes(fill=samples,colour=samples),alpha=0.5)+
  labs(x="Range of Scores",y="Probability Density",
       title="Distribution of midterm Scores by Section",
       caption="Kernel-smoothed so you won't necessarily find your actual grade",
       fill=guide_legend(title="Section"),color=guide_legend(title="Section"))

```

## Grade Distribution
```{r dist_graph,fig.width=12,fig.height=7,echo=FALSE}
all
```


## Grade Distribution By Section
```{r dist_graph_sec,fig.width=12,fig.height=7,echo=FALSE}
sec
```

## Grade Distribution By Number of Samples Completed
```{r dist_graph_samp,fig.width=12,fig.height=7,echo=FALSE}
samples
```

